#!/bin/bash
#SBATCH -J hongyu            # job name
#SBATCH -o gitm.o%j        # output and error file name (%j expands to jobID)
#SBATCH -N 4               # number of nodes requested
#SBATCH -n 144               # total number of mpi tasks requested
#SBATCH -p normal      # queue (partition) -- normal, development, etc.
#SBATCH -t 8:00:00         # run time (hh:mm:ss) - 1.5 hours
#SBATCH -A PHY21038       # Allocation name (req'd if you have more than 1)

module load netcdf/4.6.2
# run the executable named a.out                                                                    
ibrun ./GITM.exe

./pGITM
